mysite/dlmodeling/urls.py
from django.urls import path

from . import views

app_name = "dlmodeling"
urlpatterns = [
    # ex: dlmodeling/
    path('', views.index, name='index'),

    # ex: dlmodeling/summary_request
    path('summary_request', views.summary_request, name='summary_request'),

    # ex: dlmodeling/summary_run
    path('summary_run', views.summary_run, name='summary_run'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('dlmodeling/', include('dlmodeling.urls')),
    path('admin/', admin.site.urls),
]

mysite/dlmodeling/models.py
from django.db import models
from django.utils import timezone

from django.core.files.storage import FileSystemStorage


class Summary(models.Model):

    class STATUS:
        NEW = "New"
        EXE = "Executing"
        FAILED = "Failed"
        COMPLETED = "Completed"
        UNK = "Unknown"

    workload_graph = models.FileField()
    archbench_config = models.FileField()
    param_scaleup_config = models.FileField()
    enable_scaleout = models.BooleanField(default=False)
    param_scaleout_config = models.FileField(null=True)
    param_report = models.FileField(null=True)
    overlap_report = models.FileField(null=True)
    run_issue_date = models.DateTimeField(default=timezone.now())
    run_complete_date = models.DateTimeField(null=True)
    status = models.CharField(max_length=25, default=STATUS.UNK)

    config_df = models.CharField(max_length=2048, null=True)
    run_summary_df = models.CharField(max_length=2048, null=True)

    @staticmethod
    def from_request(request):
        def _get_file(fname):
            return request.FILES[fname]

        if request.method == 'POST':
            fs = FileSystemStorage()
            s = Summary()

            s.workload_graph = fs.url(fs.save(None, _get_file('workload_graph'))) if \
                _get_file('workload_graph') else None

            s.archbench_config = fs.url(fs.save(None, _get_file('archbench_config'))) if \
                _get_file('archbench_config') else None

            s.param_scaleup_config = fs.url(fs.save(None, _get_file('scaleup_config'))) if \
                _get_file('scaleup_config') else None

            s.enable_scaleout = bool(request.POST.get('enable_scaleout'))

            s.param_scaleout_config = fs.url(fs.save(None,_get_file('scaleout_config'))) if \
                _get_file('scaleout_config') else None

            s.status = Summary.STATUS.NEW
            s.save()
            return s
        else:
            return None



mysite/dlmodeling/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .models import Summary
from .viewmodels import summary_task


def index(request):
    latest_summary_runs = Summary.objects.order_by("-run_issue_date")
    context = {"latest_summary_runs": latest_summary_runs}
    return render(request, "dlmodeling/index.html", context)

def summary_request(request):
    return render(request, "dlmodeling/summary_request.html", {})

def summary_run(request):
    if request.method == 'POST':
        s = Summary.from_request(request)
        summary_task(s)
    return HttpResponseRedirect(reverse('dlmodeling:index'))

mysite/dlmodeling/templates/dlmodeling/base.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

{% load static %}

<link href="{% static 'dlmodeling/dashboard.css' %}" type="text/css" rel="stylesheet">

 <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0">
      <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="{% url 'dlmodeling:index' %}">DL Modelling</a>
      <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
      <ul class="navbar-nav px-3">
        <li class="nav-item text-nowrap">
          <a class="nav-link" href="#">Sign out</a>
        </li>
      </ul>
    </nav>

 <div class="container-fluid">
      <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
          <div class="sidebar-sticky">
            <ul class="nav flex-column">

              <li class="nav-item">
                <a class="nav-link" href="{% url 'dlmodeling:summary_request' %}">
                  <span data-feather="file"></span>
                  Summary request
                </a>
              </li>

              <li class="nav-item">
                <a class="nav-link" href="{% url 'dlmodeling:summary_request' %}">
                  <span data-feather="file"></span>
                  Sweep request
                </a>
              </li>

            </ul>

            <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
              <span>Saved reports</span>
              <a class="d-flex align-items-center text-muted" href="#">
                <span data-feather="plus-circle"></span>
              </a>
            </h6>
            <ul class="nav flex-column mb-2">
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="file-text"></span>
                  Current month
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="file-text"></span>
                  Last quarter
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="file-text"></span>
                  Social engagement
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="file-text"></span>
                  Year-end sale
                </a>
              </li>
            </ul>
          </div>
        </nav>
      </div>
 </div>

<main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
{% block page_content %}{% endblock %}
</main>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

mysite/dlmodeling/templates/dlmodeling/hw_config.html
{% load dlmodeling_extras %}

{% if run.config_df|length > 0 %}
<table class="table table-sm">
    <thead>
        <tr>
            <th scope="col">HW Parameter</th>
            {% for item in run.config_df|dictify %}
                <th>{{ item|dict_lookup:"HW Parameter" }}</th>
            {% endfor %}
        </tr>
    </thead>
    <tbody>
        <tr>
            <th scope="row">Value</th>
            {% for item in run.config_df|dictify %}
                <td>{{ item|dict_lookup:"Value" }} </td>
            {% endfor %}
        </tr>
    </tbody>
</table>
{% endif %}

mysite/dlmodeling/templates/dlmodeling/index.html
<!DOCTYPE html>
{% extends "dlmodeling/base.html" %}
<html lang="en">
<head>
   <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
</head>
<body>



{% block page_content %}

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
    <h1 class="h2">Dashboard</h1>
    <div class="btn-toolbar mb-2 mb-md-0">
        <div class="btn-group mr-2">
            <button class="btn btn-sm btn-outline-secondary">Share</button>
            <button class="btn btn-sm btn-outline-secondary">Export</button>
        </div>
        <button class="btn btn-sm btn-outline-secondary dropdown-toggle">
            <span data-feather="calendar"></span>
            This week
        </button>
    </div>
</div>


{% if latest_summary_runs %}
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Run date</th>
                <th scope="col">Status</th>
                <th scope="col">Workload</th>
                <th scope="col">Archbench config</th>
                <th scope="col">Scale-up config</th>
                <th scope="col">Enable scaleout</th>
                <th scope="col">Scale-out config</th>
                <th scope="col">Param report</th>
                <th scope="col">Overlap report</th>
                <th scope="col"> </th>
            </tr>
        </thead>
        <tbody>
        {% for run in latest_summary_runs %}
            <tr>
                <th scope="row">{{ run.id }}</th>
                <td>{{ run.run_issue_date }}</td>
                <td>{{ run.status }}</td>
                <td>{{ run.workload_graph }}</td>
                <td>{{ run.archbench_config }}</td>
                <td>{{ run.param_scaleup_config }}</td>
                <td>{{ run.enable_scaleout }}</td>
                <td>{{ run.param_scaleout_config }}</td>
                <td>{{ run.param_report }}</td>
                <td>{{ run.overlap_report}}</td>
                <td>
                    <p>
                        <a class="btn btn-primary" data-toggle="collapse" href="#collapseExample_{{ run.id }}" role="button"
                           aria-expanded="false" aria-controls="collapseExample_{{ run.id }}">
                            Details
                        </a>
                    </p>
                </td>
            </tr>
            <tr>
                <td colspan="11">
                    <div class="collapse" id="collapseExample_{{ run.id }}">
                        <div class="card card-body">
                            {% include 'dlmodeling/hw_config.html' %}
                            {% include 'dlmodeling/run_summary.html' %}
                        </div>
                    </div>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}
{% endblock %}

</body>
</html>

mysite/dlmodeling/templates/dlmodeling/run_summary.html
{% load dlmodeling_extras %}

{% if run.run_summary_df|length > 0 %}
<table class="table table-sm">
    <thead>
        <tr>
            <th scope="col">Metric</th>
            {% for item in run.run_summary_df|dictify %}
                <th>{{ item|dict_lookup:"Metric" }}</th>
            {% endfor %}
        </tr>
    </thead>
    <tbody>
        <tr>
            <th scope="row">Value</th>
            {% for item in run.run_summary_df|dictify %}
                <td>{{ item|dict_lookup:"Value" }} </td>
            {% endfor %}
        </tr>
    </tbody>
</table>
{% endif %}

mysite/dlmodeling/templates/dlmodeling/summary_request.html
<!DOCTYPE html>
{% extends "dlmodeling/base.html" %}
<html lang="en">
<head>
   <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
</head>
<body>

{% block page_content %}

<div class="card" style="width: 18rem;">
    <div class="card-header">
    Summary Analysis
    </div>
    <form class="px-4 py-3" action="{% url 'dlmodeling:summary_run' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
        <div class="form-group">
            <label for="workload_graph">Workload graph</label>
            <input type="file" class="form-control-file" id="workload_graph" name="workload_graph" required>
        </div>

        <div class="form-group">
            <label for="archbench_config">Archbench config</label>
            <input type="file" class="form-control-file" id="archbench_config" name="archbench_config" required>
        </div>

        <div class="form-group">
            <label for="scaleup_config">Scaleup config</label>
            <input type="file" class="form-control-file" id="scaleup_config" name="scaleup_config" required>
        </div>

        <div class="form-check">
            <input class="form-check-input" type="checkbox" id="enable_scaleout" name="enable_scaleout">
            <label class="form-check-label" for="enable_scaleout">
                Enable Scaleout
            </label>
        </div>

        <div class="form-group">
            <label for="scaleout_config">Scaleout config</label>
            <input type="file" class="form-control-file" id="scaleout_config" name="scaleout_config">
        </div>
    <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>

{% endblock %}

</body>
</html>